//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string SystemCnName { get; set; }
        public string SystemEnName { get; set; }
        public string Color { get; set; }
        public string Banner { get; set; }
        public string Phone { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public int AdminId { get; set; }
        public bool PushOffline { get; set; }
        public bool SMSAllow { get; set; }
        public Nullable<int> MemberId { get; set; }
    }
}
